# Generated by Django 5.0.4 on 2024-05-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_alter_purchaseorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
